apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-lab.fullname" . }}
  labels:
    {{- include "helm-lab.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "helm-lab.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
